[package]
name = "vocatype"
version = "0.1.0"
description = "VocaType - AI Voice Assistant"
authors = ["dawidkawalec"]
edition = "2021"

[lib]
name = "vocatype_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["macos-private-api"] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
fastrand = "2.0"

